### ISSUE TITLE
What version does it need?

### ISSUE THREAD

**Issue by Gfurst** [DazedMTL/Violated-Princess#6]
What version of the base game is it supposed to branch? Would it still work with 1.0EN or does it need the latest JP one?

**Comment by dazedanon** [comment]
> What version of the base game is it supposed to branch? Would it still work with 1.0EN or does it need the latest JP one?

You will need latest JP since this patch doesnt contain some of the images in the later patches.

**Comment by Gfurst** [comment]
Alright thanks for clearing it up. Might be a good idea to put the last required version to patch from.
